### ISSUE TITLE
Implement UI shown in README.md

### ISSUE THREAD

**Issue by Medini0603** [gdsc-jssstu/Park-It-Android-App#2]
## Description
The current UI of the base project is not user-friendly

##  Changes required
Refer to the UI given in README.md and implement it

**Comment by GitArya27** [comment]
please assign this issue to me

**Comment by brahma-keerthi** [comment]
Yes i have assigned, Happy coding :)

**Comment by GitArya27** [comment]
This Issue solves the #3 and #4 so shall I request for assigning the mentioned issues and complete the pull request. this would help me in Hacktoberfest.

**Comment by brahma-keerthi** [comment]
Yes, and u have successfully solved these three issues. Hence, I m closing these issues.

**Comment by brahma-keerthi** [comment]
Issue solved by @GitArya27 . Hence, closing this...
